export const ActionTypes = {
  SET_GALLERY: "SET_GALLERY",
  SET_IMAGE: "SET_IMAGE",
  /////////////////////////////
  CHANGE_HOT: "CHANGE_HOT",
  CHANGE_TOP: "CHANGE_TOP",
  CHANGE_USER: "CHANGE_USER",
  //////////////////////////////////
  CHANGE_VIRAL: "CHANGE_VIRAL",
  CHANGE_TIME: "CHANGE_TIME",
  //////////////////////////////////
  CHANGE_DAY: "CHANGE_DAY",
  CHANGE_WEEK: "CHANGE_WEEK",
  CHANGE_MONTH: "CHANGE_MONTH",
  CHANGE_YEAR: "CHANGE_YEAR",
  CHANGE_ALL: "CHANGE_ALL",
  ///////////////////////////////
  CHANGE_SHOWVIRALON: "CHANGE_SHOWVIRALON",
  CHANGE_SHOWVIRALOFF: "CHANGE_SHOWVIRALOFF",

  ///////////////////////////////
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
