export const ActionTypes = {
  SET_GALLERY: "SET_GALLERY",
  SET_IMAGE: "SET_IMAGE",
  /////////////////////////////
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
